services:
  main-service:
    container_name: main-service
    build:
      context: .
      target: app
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: "npm run start:dev"
    networks:
      - helizium-network
    ports:
      - "3501:3500"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    logging:
      options:
        max-size: 1g
    networks:
      - helizium-network
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin

networks:
  helizium-network:
    external: true
