/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

/* eslint-disable @typescript-eslint/no-empty-object-type */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export const PACKAGE_NAME = 'users';
export const SERVICE_NAME = 'UserGrpcService';

export interface UserGrpcService {
  signUp(data: SignUpMsg, metadata?: Metadata): Observable<UserIdMsg>;
  banUser(data: UserIdMsg, metadata?: Metadata): Observable<Empty>;
  unbanUser(data: UserIdMsg, metadata?: Metadata): Observable<Empty>;
  deleteUser(data: UserIdMsg, metadata?: Metadata): Observable<Empty>;
}

// tslint:disable-next-line:no-empty-interface
export interface Empty {}

export interface SignUpMsg {
  username?: string;
  email?: string;
}

export interface UserIdMsg {
  userId?: string;
}
