export enum CategoryPermissions {
  CREATE = 'CREATE',
  EDIT = 'EDIT',
  PIN = 'PIN',
  UNPIN = 'UNPIN',
  DELETE = 'DELETE',
  EDIT_SELF = 'EDIT_SELF',
  DELETE_SELF = 'DELETE_SELF',
  VIEW_DELETED = 'VIEW_DELETED',
  VIEW_DELETED_SELF = 'VIEW_DELETED_SELF',
  RESTORE = 'RESTORE',
  RESTORE_SELF = 'RESTORE_SELF',
}
