export enum TokenLimits {
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  MFA_REQUIRED = 'MFA_REQUIRED',
  USER_BANNED = 'USER_BANNED',
  READ_ONLY = 'READ_ONLY',
  DEFAULT = 'DEFAULT',
  ROOT = 'ROOT',
  BANNED_ROOT = 'BANNED_ROOT',
}
