export enum TopicTypes {
  TAKE_AND_COMPLETE = 'TAKE_AND_COMPLETE',
  BEST_WORK = 'BEST_WORK',
  SELL_TO_SINGLE_PERSON = 'SELL_TO_SINGLE_PERSON',
  SELL_FOR_MANY_PEOPLE = 'SELL_FOR_MANY_PEOPLE',
  DISCUSSION = 'DISCUSSION',
}
